// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Js_exn = require("rescript/lib/js/js_exn.js");
var Nodehttp = require("node:http");
var Caml_js_exceptions = require("rescript/lib/js/caml_js_exceptions.js");

var server = Nodehttp.createServer(function (request, response) {
      var url = request.url;
      var headers = request.headers;
      console.log(url);
      console.log(headers);
      request.on("data", (function (data) {
              var str = data.toString();
              try {
                var json = JSON.parse(str);
                if (!Array.isArray(json) && (json === null || typeof json !== "object") && typeof json !== "number" && typeof json !== "string" && typeof json !== "boolean") {
                  console.log("not an object");
                  return ;
                }
                if (typeof json === "object" && !Array.isArray(json)) {
                  console.log(json);
                  return ;
                }
                console.log("not an object");
                return ;
              }
              catch (raw_exn){
                var exn = Caml_js_exceptions.internalToOCamlException(raw_exn);
                if (exn.RE_EXN_ID === Js_exn.$$Error) {
                  console.log("error");
                  return ;
                }
                throw exn;
              }
            }));
      request.pipe(response);
    });

exports.server = server;
/* server Not a pure module */
